spring:
  application:
    name: DBApi-cluster-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: api_route
          uri: lb://DBApi-cluster-apiServer
          predicates:
            - Path=/api/**
server:
  port: 8525