
spring:
  application:
    name: DBApi-cluster-gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: lb://DBApi-cluster-apiServer
          predicates:
            - Path=/${dbapi.api.context}/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: '*'
            allowed-methods: '*'
            allowed-headers: "*"

server:
  port: 8525
logging:
  config: classpath:logback-gateway.xml